version: '3'
#https://github.com/Landoop/fast-data-dev
#https://hub.docker.com/r/nshou/elasticsearch-kibana/
#https://github.com/deviantony/docker-elk

services:
  kafka-cluster:
    image: landoop/fast-data-dev:latest
    environment: 
      CONNECT_HEAP: 1G
      ADV_HOST: 127.0.0.1
      RUNTESTS: 0
    ports:
      - 2181:2181
      - 3030:3030
      - 8081-8083:8081-8083
      - 9581-9585:9581-9585
      - 9092:9092
  

  elasticsearch:
      image: itzg/elasticsearch:2.4.3
      environment:
        ES_JAVA_OPTS: "-Xmx1g -Xms1g"
        PLUGINS: appbaseio/dejavu
        OPTS: -Dindex.number_of_shards=1 -Dindex.number_of_replicas=0
      ports:
        - 9200:9200



  postgres:
    image: postgres:10-alpine
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
